### ISSUE TITLE
responsive sidebar

### ISSUE THREAD

**Issue by alexisargyris** [adarshpastakia/aurelia-ui-framework#39]
First of all congratulations for your amazing work!

I need to have a `ui-sidebar` with variable width (i.e. responsive). I tried something like this:

```
<ui-page page-title="page">
    <ui-section row-layout>
      <ui-sidebar label="options" scroll collapsible style="flex: 1 1 0;">
        here go the options
      </ui-sidebar>
      <ui-content padded scroll style="flex: 2 1 0;">
        here goes the content
      </ui-content>
    </ui-section>
</ui-page>
```

This doesn't work probably because `ui-sidebar`'s default styling includes `max-width = 15em`. I tried to change this (e.g. set it to `none `or some other value) either by css or code. This works (the sidebar's width does change) but then the sidebar stops collapsing.

Am I doing something wrong? Is this a bug?

Thanks

**Comment by alexisargyris** [comment]
Switched machines and cannot reproduce it anymore. Setting `max-width = none` seems to work fine now. Thanks anyway.

**Comment by adarshpastakia** [comment]
@alexisargyris the reason for max-width was to animate the collapse on, i haven't tried it but you could try, however when displaying the collapsed sidebar `width:15em` will come into affect

```css
.ui-section.flexi-sidebar .ui-sidebar {
max-width:none;
transition-property: all;
flex: 1 1 0em;
}
.ui-section.flexi-sidebar .ui-sidebar.ui-collapse {
max-width: none;
flex: 0 0 2em;
}
/* Incase you wish to change the size of the collapse content overlay */
.ui-section.flexi-sidebar .ui-sidebar.ui-collapse .ui-sidebar-content {
width: 20em;
left: -20em;
}
.ui-section.flexi-sidebar .ui-content {
flex: 2 1 0em;
}
```

```html
<ui-section class="flexi-sidebar">
 <ui-sidebar collapsible>..<ui-sidebar>
 <ui-content>..</ui-content>
</ui-section>
```
